export const  InitColor = [
  {
    title_text: 'Appwall Test',
    title_text_color: '#FFFFFF',
    title_background_color: '#234582',
    subtitle_text: 'No Downloads, Earn more',
    subtitle_color: '#FFFFFF',
    subtitle_background_color: '#132E61',
    ad_title_color: '#FFD635',
    ad_desc_color: '#FFFFFF',
    ad_edge_color: '#132E61',
    ad_background_color: '#132E61',
    button_text_color: '#FFFFFF',
    button_background_color: '#FF9600',
    button_edge_color: '#FF9600',
    button_unavail_color: '#666666',
    big_background_color: '#234582'
  },
  {
    title_text: 'Appwall Test',
    title_text_color: '#FFFFFF',
    title_background_color: '#234582',
    subtitle_text: 'No Downloads, Earn more',
    subtitle_color: '#FFFFFF',
    subtitle_background_color: '#234582',
    ad_title_color: '#FFD635',
    ad_desc_color: '#FFFFFF',
    ad_edge_color: '#132E61',
    ad_background_color: '#132E61',
    button_text_color: '#FFFFFF',
    button_background_color: '#FF9600',
    button_edge_color: '#FF9600',
    button_unavail_color: '#666666',
    big_background_color: '#234582'
  },
  {
    title_text: 'Appwall Test',
    title_text_color: '#FFFFFF',
    title_background_color: '#1BB8FF',
    subtitle_text: 'No Downloads, Earn more',
    subtitle_color: '#333333',
    subtitle_background_color: '#FFFFFF',
    ad_title_color: '#666666',
    ad_desc_color: '#666666',
    ad_edge_color: '#FFFFFF',
    ad_background_color: '#FFFFFF',
    button_text_color: '#FFFFFF',
    button_background_color: '#FF9600',
    button_edge_color: '#FF9600',
    button_unavail_color: '#666666',
    big_background_color: '#1BB8FF'
  },
  {
    title_text: 'Appwall Test',
    title_text_color: '#FFFFFF',
    title_background_color: '#234582',
    subtitle_text: 'No Downloads, Earn more',
    subtitle_color: '#FFFFFF',
    subtitle_background_color: '#132E61',
    ad_title_color: '#666666',
    ad_desc_color: '#666666',
    ad_edge_color: '#FFFFFF',
    ad_background_color: '#FFFFFF',
    button_text_color: '#FFFFFF',
    button_background_color: '#FF9600',
    button_edge_color: '#FF9600',
    button_unavail_color: '#666666',
    big_background_color: '#234582'
  },
  {
    title_text: 'Appwall Test',
    title_text_color: '#FFFFFF',
    title_background_color: '#F6F5FB',
    subtitle_text: 'No Downloads, Earn more',
    subtitle_color: '#ADADB1',
    subtitle_background_color: '#F6F5FB',
    ad_title_color: '#3D4555',
    ad_desc_color: '#A6A6A9',
    ad_edge_color: '#FFFFFF',
    ad_background_color: '#FFFFFF',
    button_text_color: '#FFFFFF',
    button_background_color: '#377BF6',
    button_edge_color: '#377BF6',
    button_unavail_color: '#666666',
    big_background_color: '#F6F5FB'
  },

]