// This file is automatically generated.
// Please do not change this file!
export const GroupBox: string;
export const boxTitle: string;
export const btn2: string;
export const btnBox: string;
export const campaignFilter: string;
export const campaignFilterWrap: string;
export const colorFont: string;
export const companyTag: string;
export const currencyModal: string;
export const formItemBox: string;
export const hasImg: string;
export const imgBox: string;
export const imgTitle: string;
export const item: string;
export const lineSpan: string;
export const lineSpanOr: string;
export const noTitle: string;
export const picture: string;
export const tagWrapper: string;
export const text: string;
export const uploadBtn: string;
export const uploadICON: string;
export const vcId: string;
export const workBtn: string;
