// This file is automatically generated.
// Please do not change this file!
export const Chart: string;
export const RadioBox: string;
export const Search: string;
export const box: string;
export const page: string;
