// This file is automatically generated.
// Please do not change this file!
export const imageInfo: string;
export const imageList: string;
export const imagelistImg: string;
export const viewModal: string;
