// This file is automatically generated.
// Please do not change this file!
export const CompanyModal: string;
export const btn: string;
export const btn2: string;
export const btnBox: string;
export const disable: string;
export const modalBtn: string;
export const tableBox: string;
export const tableContainer: string;
export const workPlus: string;
