// This file is automatically generated.
// Please do not change this file!
export const FirstScene: string;
export const SceneList: string;
export const closeIcon: string;
export const dynamic: string;
export const formItemClassName: string;
export const img: string;
export const imgBox: string;
export const imgList: string;
export const label: string;
export const linkUrl: string;
export const linkUrlWrapper: string;
export const select: string;
export const titleGroup: string;
export const uploadGroup: string;
export const zheZhao: string;
