// This file is automatically generated.
// Please do not change this file!
export const bottom: string;
export const btnBox: string;
export const busbox: string;
export const card: string;
export const frame: string;
export const label: string;
export const left: string;
export const list: string;
export const list1: string;
export const main: string;
export const msg: string;
export const right: string;
export const tab: string;
export const table: string;
export const title: string;
export const tt: string;
export const value: string;
export const vv: string;
