// This file is automatically generated.
// Please do not change this file!
export const btnBox: string;
export const categoryList: string;
export const frequency: string;
export const optionText: string;
export const showExtra: string;
export const taskModal: string;
