// This file is automatically generated.
// Please do not change this file!
export const captcha: string;
export const form: string;
export const login: string;
export const logoBox: string;
export const tips: string;
