// This file is automatically generated.
// Please do not change this file!
export const box: string;
export const fileBox: string;
export const fileIcon: string;
export const fileName: string;
export const imgBox: string;
export const layer: string;
export const trueDom: string;
