// This file is automatically generated.
// Please do not change this file!
export const box: string;
export const fileBox: string;
export const fileIcon: string;
export const fileName: string;
export const frame: string;
export const imgBox: string;
export const label: string;
export const layer: string;
export const linkUrl: string;
export const linkUrlWrapper: string;
export const onlineWrap: string;
export const trueDom: string;
export const videoWrapper: string;
