// This file is automatically generated.
// Please do not change this file!
export const colClass: string;
export const container: string;
export const popovers: string;
export const tableBox: string;
export const textHidden: string;
