// This file is automatically generated.
// Please do not change this file!
export const appForm: string;
export const btnBox: string;
export const btnGroup: string;
export const longLabel: string;
export const submitBtn: string;
export const uploadICON: string;
export const workBtn: string;
export const workPlus: string;
