// This file is automatically generated.
// Please do not change this file!
export const btn2: string;
export const btnBox: string;
export const currencyModal: string;
export const importBtn: string;
export const uploadICON: string;
export const vcMdoal: string;
export const workBtn: string;
export const workPlus: string;
