// This file is automatically generated.
// Please do not change this file!
export const box: string;
export const dynamic: string;
export const errmsg: string;
export const help: string;
export const inputBox: string;
export const minInput: string;
export const radio: string;
export const redio: string;
export const tree: string;
export const workBtn: string;
export const xia: string;
