// This file is automatically generated.
// Please do not change this file!
export const colClass: string;
export const container: string;
export const linkBtn: string;
export const remarkBtn: string;
export const tableBox: string;
export const taskTable: string;
