// This file is automatically generated.
// Please do not change this file!
export const CompanyModal: string;
export const btn2: string;
export const btnBox: string;
export const companyTag: string;
export const tagWrapper: string;
