// This file is automatically generated.
// Please do not change this file!
export const container: string;
export const linkBtn: string;
export const popoverContent: string;
export const tableBox: string;
