// This file is automatically generated.
// Please do not change this file!
export const dark: string;
export const logoBox: string;
export const menu: string;
export const sideBarIcon: string;
export const sider: string;
