// This file is automatically generated.
// Please do not change this file!
export const configModal: string;
export const head: string;
export const row: string;
export const title: string;
export const value: string;
