// This file is automatically generated.
// Please do not change this file!
export const btn2: string;
export const btnBox: string;
export const floatBlock: string;
export const templateModal: string;
export const textItem: string;
export const uploadArea: string;
export const uploadBtn: string;
export const uploadIcon: string;
