// This file is automatically generated.
// Please do not change this file!
export const addbtn: string;
export const box: string;
export const btnGroup: string;
export const head: string;
export const row: string;
export const submitBtn: string;
export const title: string;
export const value: string;
