// This file is automatically generated.
// Please do not change this file!
export const box: string;
export const dynamic: string;
export const input: string;
export const inputBox: string;
export const redio: string;
