// This file is automatically generated.
// Please do not change this file!
export const container: string;
export const expantCell: string;
export const expantTable: string;
export const tableBox: string;
