// This file is automatically generated.
// Please do not change this file!
export const GroupBox: string;
export const UploadBox: string;
export const autoHeight: string;
export const btn2: string;
export const btnBox: string;
export const btnUpload: string;
export const btnUploadGroup: string;
export const btnUploadTitle: string;
export const endcardModal: string;
export const full: string;
export const hasImg: string;
export const heng: string;
export const imgBox: string;
export const imgTitle: string;
export const imgbox: string;
export const shu: string;
export const sunjiao: string;
export const title: string;
export const vcMdoal: string;
