// This file is automatically generated.
// Please do not change this file!
export const GroupBox: string;
export const btn2: string;
export const btnBox: string;
export const endcardModal: string;
export const hasImg: string;
export const imgBox: string;
export const imgTitle: string;
export const vcMdoal: string;
